### ISSUE TITLE
add python-apollo test to action

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#2569]

**Comment by nathandunn** [comment]
```
  py_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Python install
      run: |
        pip install -U pip setuptools nose
        python setup.py install
    - name: Launch containers
      run: |
        export ARROW_GLOBAL_CONFIG_PATH=`pwd`/test-data/arrow.yml
        ./bootstrap_apollo.sh
    - name: Run tests
      run: |
        export ARROW_GLOBAL_CONFIG_PATH=`pwd`/test-data/arrow.yml
        python setup.py nosetests
```
